name: neural_fingerprint_env
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - pip
  - pip:
      - foolbox
      - cleverhans
      - torchprune  # If available; otherwise, implement pruning manually
